### ISSUE TITLE
The main container is exited after the POD container is killed

### ISSUE THREAD

**Issue by dieuroi** [GoogleCloudPlatform/kubernetes#11223]
I use docker version 1.2 and kubernetes v0.20.2 on os SUSE.
I made a image called suse13.1/apache and service apache will start once container is created.
My json file for creating a pod is as follows.
```
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "suseapache",
    "labels": {
	  "name":"suseapache"
	}
  },
  "spec": {
    "containers": [{
      "name": "suseapache",
      "image": "suse13.1/apache",
	  "imagepullPolicy": "Never",
      "ports": [{
		"containerPort": 80
	  }] 
    }],
    "restartPolicy": "Never"
  }
}
```

And I use **google/pause:go** instead of gcr.io/google_container/pause. The pod is created but still not ready:

```
NAME         READY     REASON    RESTARTS   AGE
suseapache   0/1       Running     0          4s
```

After a while, the pod is exited.

```
NAME         READY     REASON       RESTARTS   AGE
suseapache   0/1       ExitCode:0   0          11s
```

The describe of the pod say:
 
>Events:
  FirstSeen				LastSeen			Count	From			SubobjectPath				Reason		Message
  Tue, 14 Jul 2015 20:38:45 +0800	Tue, 14 Jul 2015 20:38:45 +0800	1	{scheduler }							scheduled	Successfully assigned suseapache to localhost
  Tue, 14 Jul 2015 20:38:45 +0800	Tue, 14 Jul 2015 20:38:45 +0800	1	{kubelet localhost}	implicitly required container POD	pulled		Pod container image "google/pause:go" already present on machine
  Tue, 14 Jul 2015 20:38:45 +0800	Tue, 14 Jul 2015 20:38:45 +0800	1	{kubelet localhost}	implicitly required container POD	created		Created with docker id 8b65151c8b49
  Tue, 14 Jul 2015 20:38:45 +0800	Tue, 14 Jul 2015 20:38:45 +0800	1	{kubelet localhost}	implicitly required container POD	started		Started with docker id 8b65151c8b49
  Tue, 14 Jul 2015 20:38:46 +0800	Tue, 14 Jul 2015 20:38:46 +0800	1	{kubelet localhost}	spec.containers{suseapache}		created		Created with docker id 4224f3bc09d2
  Tue, 14 Jul 2015 20:38:46 +0800	Tue, 14 Jul 2015 20:38:46 +0800	1	{kubelet localhost}	spec.containers{suseapache}		started		Started with docker id 4224f3bc09d2
  Tue, 14 Jul 2015 20:38:55 +0800	Tue, 14 Jul 2015 20:38:55 +0800	1	{kubelet localhost}	implicitly required container POD	killing		**Killing with docker id 8b65151c8b49**

**Comment by thockin** [comment]
Docker 1.2 is pretty old and not well tested any longer - I would suggest
you upgrade to 1.6.2.

Kubernetes 0.20 is not THAT old but still old in kube-time :)

Why are you using a different pause container?  Why do we HAVE a different
pause container in the google/ namespace?

As for the issue - if the pause container dies, all containers in the pod
must be restarted.  I don't know why it is dying, but it could be that any
bugs that have been fixed are fixed in the standard pause container, nit
that other one.

**Comment by dchen1107** [comment]
@dieuroi I am surprised that docker 1.2 is still working in your environment. Actually the minimal docker remote API version kubelet support is 1.15, which should map to docker 1.3 at least. The recent validated docker version we used is docker 1.6.2, remote API version is 1.18. Also when pause container dies, all containers in the pod should be killed, and recreated after pause is restarted. This is expected behavior. But I am not sure why your pause container is dead.

**Comment by erictune** [comment]
@dieuroi feel free to reopen issue if you still have an issue after upgrading docker.

**Comment by dieuroi** [comment]
After upgrading docker to version 1.6.2 and using docker.io/kubernetes/pause as pause container. But the issue still exists.

**Comment by thockin** [comment]
Can you clarify what the problem is?  WHat did you expect to happen and
what actually happened?

**Comment by dieuroi** [comment]
I upgraded docker to version 1.6.2 and used docker.io/kubernetes/pause as pause container.
I made a image called suse13.1/apache and service apache will start once container is created.
My json file for creating a pod is as follows.
```
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "suseapache",
    "labels": {
	  "name":"suseapache"
	}
  },
  "spec": {
    "containers": [{
      "name": "suseapache",
      "image": "suse13.1/apache",
	  "imagepullPolicy": "Never",
      "ports": [{
		"containerPort": 80
	  }] 
    }],
    "restartPolicy": "Always"
  }
}
```

After I running *kubectl create -f* with this file, the main container would be created and started again and again. I ran *docker ps -a" to find main containers created before were exit.

```
CONTAINER ID        IMAGE                     COMMAND                CREATED             STATUS                      PORTS               NAMES
aecb3464e797        suse13.1/apache:latest    "/bin/sh -c 'service   8 seconds ago       Exited (0) 4 seconds ago                        k8s_suseapache.10eaed5c_suseapache_default_17e551eb-2aaa-11e5-a4ef-080027fc4f03_afd5f8e7   
10ebe757b517        suse13.1/apache:latest    "/bin/sh -c 'service   19 seconds ago      Exited (0) 14 seconds ago                       k8s_suseapache.10eaed5c_suseapache_default_17e551eb-2aaa-11e5-a4ef-080027fc4f03_59483787   
bfcf7e1072de        suse13.1/apache:latest    "/bin/sh -c 'service   28 seconds ago      Exited (0) 24 seconds ago                       k8s_suseapache.10eaed5c_suseapache_default_17e551eb-2aaa-11e5-a4ef-080027fc4f03_6bf054d5   
066b8c52bcde        kubernetes/pause:latest   "/pause"               29 seconds ago      Up 28 seconds                                   k8s_POD.6c71e49f_suseapache_default_17e551eb-2aaa-11e5-a4ef-080027fc4f03_675ffc22  
```

**Comment by thockin** [comment]
Your suse13.1/apache:latest container is exiting and being restarted.  You
might look at logs for the exited containers to see why.

**Comment by dieuroi** [comment]
Does that mean something is wrong with my suse13.1/apache:latest container, not kubernetes?

**Comment by thockin** [comment]
Correct.  It seems that kubelet is doing what you asked it to do: run a
container and restart it whenever it dies.

**Comment by dieuroi** [comment]
Thank you ! @thockin  I will go to check the log.
