### ISSUE TITLE
bug: kubelet etcd watch errors

### ISSUE THREAD

**Issue by sym3tri** [GoogleCloudPlatform/kubernetes#4141]
I spun up a k8s cluster on CoreOS using [https://github.com/pires/kubernetes-vagrant-coreos-cluster](this vagrant setup). I was able to create & list Pods, but the Pod containers would never get launched. The kubelet log showed what looks like an issue with an etcd watcher. Note the 'key modified index' is much lower than the cluster index (cluster: 26286, key: 19255), meaning the watch will never get triggered. I understand this is a known issue in etcd, and it cannot be fixed correctly without major changes to the data model. To work around this, the kubernetes watchers need to be using the cluster index when creating watchers rather than the key's modified index.

Manual Workaround: "touch" the etcd key by doing:
```
etcdctl get /registry/nodes/172.17.8.102/boundpods | etcdctl set /registry/nodes/172.17.8.102/boundpods
```

kubelet logs:

```
Feb 04 22:02:03 node-01 kubelet[17799]: I0204 22:02:03.039952   17799 etcd.go:78] Watch closed (&api.Status{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ListMeta:api.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"401: The event in requested index is outdated and cleared (the requested history has been cleared [26284/19255]) [27283]", Reason:"", Details:(*api.StatusDetails)(nil), Code:0}). Reopening.
Feb 04 22:02:04 node-01 kubelet[17799]: I0204 22:02:04.040393   17799 logs.go:40] etcd DEBUG: get /registry/nodes/172.17.8.102/boundpods [http://172.17.8.101:4001]
Feb 04 22:02:04 node-01 kubelet[17799]: I0204 22:02:04.040452   17799 logs.go:40] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/nodes/172.17.8.102/boundpods?consistent=true&recursive=false&sorted=false
Feb 04 22:02:04 node-01 kubelet[17799]: I0204 22:02:04.040462   17799 logs.go:40] etcd DEBUG: send.request.to http://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&recursive=false&sorted=false | method GET
Feb 04 22:02:04 node-01 kubelet[17799]: I0204 22:02:04.041716   17799 logs.go:40] etcd DEBUG: recv.response.fromhttp://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&recursive=false&sorted=false
Feb 04 22:02:04 node-01 kubelet[17799]: I0204 22:02:04.041748   17799 logs.go:40] etcd DEBUG: recv.success.http://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&recursive=false&sorted=false
Feb 04 22:02:04 node-01 kubelet[17799]: I0204 22:02:04.048829   17799 logs.go:40] etcd DEBUG: watch /registry/nodes/172.17.8.102/boundpods [http://172.17.8.101:4001]
Feb 04 22:02:04 node-01 kubelet[17799]: I0204 22:02:04.050031   17799 logs.go:40] etcd DEBUG: get /registry/nodes/172.17.8.102/boundpods [http://172.17.8.101:4001]
Feb 04 22:02:04 node-01 kubelet[17799]: I0204 22:02:04.050793   17799 logs.go:40] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/nodes/172.17.8.102/boundpods?consistent=true&wait=true&waitIndex=19255
Feb 04 22:02:04 node-01 kubelet[17799]: I0204 22:02:04.051116   17799 logs.go:40] etcd DEBUG: send.request.to http://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&wait=true&waitIndex=19255 | method GET
Feb 04 22:02:04 node-01 kubelet[17799]: I0204 22:02:04.053068   17799 logs.go:40] etcd DEBUG: recv.response.fromhttp://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&wait=true&waitIndex=19255
Feb 04 22:02:04 node-01 kubelet[17799]: I0204 22:02:04.053375   17799 logs.go:40] etcd DEBUG: recv.success.http://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&wait=true&waitIndex=19255
Feb 04 22:02:04 node-01 kubelet[17799]: I0204 22:02:04.053659   17799 etcd.go:78] Watch closed (&api.Status{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ListMeta:api.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"401: The event in requested index is outdated and cleared (the requested history has been cleared [26285/19255]) [27284]", Reason:"", Details:(*api.StatusDetails)(nil), Code:0}). Reopening.
Feb 04 22:02:05 node-01 kubelet[17799]: I0204 22:02:05.054636   17799 logs.go:40] etcd DEBUG: get /registry/nodes/172.17.8.102/boundpods [http://172.17.8.101:4001]
Feb 04 22:02:05 node-01 kubelet[17799]: I0204 22:02:05.054718   17799 logs.go:40] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/nodes/172.17.8.102/boundpods?consistent=true&recursive=false&sorted=false
Feb 04 22:02:05 node-01 kubelet[17799]: I0204 22:02:05.054748   17799 logs.go:40] etcd DEBUG: send.request.to http://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&recursive=false&sorted=false | method GET
Feb 04 22:02:05 node-01 kubelet[17799]: I0204 22:02:05.056090   17799 logs.go:40] etcd DEBUG: recv.response.fromhttp://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&recursive=false&sorted=false
Feb 04 22:02:05 node-01 kubelet[17799]: I0204 22:02:05.056133   17799 logs.go:40] etcd DEBUG: recv.success.http://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&recursive=false&sorted=false
Feb 04 22:02:05 node-01 kubelet[17799]: I0204 22:02:05.059809   17799 logs.go:40] etcd DEBUG: watch /registry/nodes/172.17.8.102/boundpods [http://172.17.8.101:4001]
Feb 04 22:02:05 node-01 kubelet[17799]: I0204 22:02:05.061249   17799 logs.go:40] etcd DEBUG: get /registry/nodes/172.17.8.102/boundpods [http://172.17.8.101:4001]
Feb 04 22:02:05 node-01 kubelet[17799]: I0204 22:02:05.061287   17799 logs.go:40] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/nodes/172.17.8.102/boundpods?consistent=true&wait=true&waitIndex=19255
Feb 04 22:02:05 node-01 kubelet[17799]: I0204 22:02:05.061297   17799 logs.go:40] etcd DEBUG: send.request.to http://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&wait=true&waitIndex=19255 | method GET
Feb 04 22:02:05 node-01 kubelet[17799]: I0204 22:02:05.063736   17799 logs.go:40] etcd DEBUG: recv.response.fromhttp://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&wait=true&waitIndex=19255
Feb 04 22:02:05 node-01 kubelet[17799]: I0204 22:02:05.063769   17799 logs.go:40] etcd DEBUG: recv.success.http://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&wait=true&waitIndex=19255
Feb 04 22:02:05 node-01 kubelet[17799]: I0204 22:02:05.063830   17799 etcd.go:78] Watch closed (&api.Status{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ListMeta:api.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"401: The event in requested index is outdated and cleared (the requested history has been cleared [26285/19255]) [27284]", Reason:"", Details:(*api.StatusDetails)(nil), Code:0}). Reopening.
Feb 04 22:02:06 node-01 kubelet[17799]: I0204 22:02:06.067255   17799 logs.go:40] etcd DEBUG: get /registry/nodes/172.17.8.102/boundpods [http://172.17.8.101:4001]
Feb 04 22:02:06 node-01 kubelet[17799]: I0204 22:02:06.067314   17799 logs.go:40] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/nodes/172.17.8.102/boundpods?consistent=true&recursive=false&sorted=false
Feb 04 22:02:06 node-01 kubelet[17799]: I0204 22:02:06.067324   17799 logs.go:40] etcd DEBUG: send.request.to http://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&recursive=false&sorted=false | method GET
Feb 04 22:02:06 node-01 kubelet[17799]: I0204 22:02:06.068758   17799 logs.go:40] etcd DEBUG: recv.response.fromhttp://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&recursive=false&sorted=false
Feb 04 22:02:06 node-01 kubelet[17799]: I0204 22:02:06.068792   17799 logs.go:40] etcd DEBUG: recv.success.http://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&recursive=false&sorted=false
Feb 04 22:02:06 node-01 kubelet[17799]: I0204 22:02:06.073435   17799 logs.go:40] etcd DEBUG: watch /registry/nodes/172.17.8.102/boundpods [http://172.17.8.101:4001]
Feb 04 22:02:06 node-01 kubelet[17799]: I0204 22:02:06.073674   17799 logs.go:40] etcd DEBUG: get /registry/nodes/172.17.8.102/boundpods [http://172.17.8.101:4001]
Feb 04 22:02:06 node-01 kubelet[17799]: I0204 22:02:06.074112   17799 logs.go:40] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/nodes/172.17.8.102/boundpods?consistent=true&wait=true&waitIndex=19255
Feb 04 22:02:06 node-01 kubelet[17799]: I0204 22:02:06.075787   17799 logs.go:40] etcd DEBUG: send.request.to http://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&wait=true&waitIndex=19255 | method GET
Feb 04 22:02:06 node-01 kubelet[17799]: I0204 22:02:06.076988   17799 logs.go:40] etcd DEBUG: recv.response.fromhttp://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&wait=true&waitIndex=19255
Feb 04 22:02:06 node-01 kubelet[17799]: I0204 22:02:06.077013   17799 logs.go:40] etcd DEBUG: recv.success.http://172.17.8.101:4001/v2/keys/registry/nodes/172.17.8.102/boundpods?consistent=true&wait=true&waitIndex=19255
Feb 04 22:02:06 node-01 kubelet[17799]: I0204 22:02:06.077064   17799 etcd.go:78] Watch closed (&api.Status{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ListMeta:api.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"401: The event in requested index is outdated and cleared (the requested history has been cleared [26286/19255]) [27285]", Reason:"", Details:(*api.StatusDetails)(nil), Code:0}). Reopening.
```

**Comment by erictune** [comment]
I'll either fix the CoreOS scripts so that the kubelets don't use etcd, or talk someone into doing it.  That will indirectly fix this issue  So, I'll pick up this issue.

**Comment by bcwaldon** [comment]
@erictune There's clearly something wrong here, so I'm more than happy to dig into it and get the real fix together if you prefer.

**Comment by pires** [comment]
This has been fixed recently with #4708, right?

**Comment by erictune** [comment]
Right.

**Comment by erictune** [comment]
@sym3tri we think if you update your config to #4708 that you won't see this.

**Comment by erictune** [comment]
Please feel free to reopen if not.

**Comment by bcwaldon** [comment]
I don't believe this issue is really *solved* by moving away from the etcd watcher. CoreOS clusters are more likely to have other clients of etcd, which causes the etcd index to increase faster than it may on non-CoreOS problems. This issue, however, is caused by shared usage of an etcd cluster - it is not specific to the CoreOS platform. As far as I am concerned, this bug is not fixed by #4708, only treated in this specific case and only for those using the CoreOS guide (which I am not).
