### ISSUE TITLE
Kubelet not robust to docker not running?

### ISSUE THREAD

**Issue by alex-mohr** [GoogleCloudPlatform/kubernetes#5411]
With version 0.12.1 on GKE, a node came up, but kubelet never served on :10250 -- connection refused.

From the logs, the most suspicious line is:
E0311 20:06:01.137166    4797 server.go:299] Failed to create kubelet: dial unix /var/run/docker.sock: connection refused

If that happens, kubelet is unhealthy, but it doesn't terminate.  It never serves, master's /validate reports:
  {
    "component": "node-2",
    "health": "unknown",
    "healthCode": 2,
    "err": "Get http://k8s-staging-regtest-loop-2015-03-11-13-03-21-node-3.c.cloud-kubernetes-dev.internal:10250/healthz: dial tcp 10.240.127.26:10250: connection refused"
  },

killing the kubelet process results in it exiting, followed by monit restarting it, and the node going healthy.

From the process list, I suspect a race between docker start and kubelet start given docker.pid > kubelet.pid?
root      2267  0.0  0.3  64672 14660 ?        Sl   23:10   0:00 /usr/local/bin/kubelet --api_servers=https://10.240.126.17:6443 --auth_path=/var/lib/kubelet/kubernetes_auth --address=0.0.0.0 --config=/etc/kubernetes/manifests --allow_privileged=False --v=2 --cluster_dns=
10.103.240.10 --cluster_domain=kubernetes.local
ntp       2296  0.0  0.1  34876  4280 ?        Ss   23:10   0:00 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -c /var/lib/ntp/ntp.conf.dhcp -u 101:103
root      2363  0.0  0.0  52260  2868 ?        Ss   23:10   0:00 /usr/sbin/sshd
root      2515  0.0  0.1  79780  5600 ?        Ss   23:10   0:00 sshd: mohr [priv]
mohr      2535  0.0  0.1  79780  4312 ?        S    23:10   0:00 sshd: mohr@pts/2 
mohr      2572  0.0  0.0  19412  3440 pts/2    Ss   23:10   0:00 -bash
root      2783  0.0  0.3 190880 14016 ?        Sl   23:10   0:00 /usr/bin/docker -d -p /var/run/docker.pid --insecure-registry 10.0.0.0/8 --insecure-registry 172.16.0.0/12 --registry-mirror='https://us-central1.docker-cache.clustermaster.net' --bridge cbr0 --iptables=fals
e --ip-masq=false

And here's /var/run/kubelet.log
I0311 20:05:03.952314    2370 node.go:52] Connecting to docker on unix:///var/run/docker.sock
I0311 20:05:03.952378    2370 util.go:129] No api servers specified.
I0311 20:05:03.953594    2370 standalone.go:194] Adding manifest file: /etc/kubernetes/manifests
I0311 20:05:03.953627    2370 standalone.go:200] Adding manifest url: http://metadata.google.internal/computeMetadata/v1beta1/instance/attributes/google-container-manifest
I0311 20:05:03.958922    2370 plugins.go:56] Registering credential provider: .dockercfg
I0311 20:05:03.960508    2370 event.go:92] Event(api.ObjectReference{Kind:"Minion", Namespace:"default", Name:"k8s-staging-regtest-loop-2015-03-11-13-03-21-node-3.c.cloud-kubernetes-dev.internal", UID:"k8s-staging-regtest-loop-2015-03-11-13-03-21-node-3.c.cloud-kubernetes
-dev.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}): status: '', reason: 'starting' Starting kubelet.
I0311 20:05:03.975362    2370 plugins.go:56] Registering credential provider: google-dockercfg
I0311 20:05:03.976790    2370 plugins.go:56] Registering credential provider: google-dockercfg-url
E0311 20:05:03.976907    2370 http.go:54] Failed to read URL: http://metadata.google.internal/computeMetadata/v1beta1/instance/attributes/google-container-manifest: 404 Not Found
I0311 20:05:03.979434    2370 plugins.go:56] Registering credential provider: google-container-registry
I0311 20:05:04.032270    2370 event.go:92] Event(api.ObjectReference{Kind:"BoundPod", Namespace:"default", Name:"cadvisor-agent", UID:"cadvisormanifes12uqn2ohido76855gdecd9roadm7l0", APIVersion:"v1beta2", ResourceVersion:"", FieldPath:"implicitly required container net"})
: status: 'waiting', reason: 'pulled' Successfully pulled image "kubernetes/pause:latest"
I0311 20:05:04.205702    2370 event.go:92] Event(api.ObjectReference{Kind:"BoundPod", Namespace:"default", Name:"cadvisor-agent", UID:"cadvisormanifes12uqn2ohido76855gdecd9roadm7l0", APIVersion:"v1beta2", ResourceVersion:"", FieldPath:"implicitly required container net"})
: status: 'waiting', reason: 'created' Created with docker id 8a67dd6b14f37d173ad9836a9f5980360328b7b526fa7f0a57bd513ef48765cd
I0311 20:05:05.409658    2370 event.go:92] Event(api.ObjectReference{Kind:"BoundPod", Namespace:"default", Name:"cadvisor-agent", UID:"cadvisormanifes12uqn2ohido76855gdecd9roadm7l0", APIVersion:"v1beta2", ResourceVersion:"", FieldPath:"implicitly required container net"})
: status: 'running', reason: 'started' Started with docker id 8a67dd6b14f37d173ad9836a9f5980360328b7b526fa7f0a57bd513ef48765cd
I0311 20:05:05.536258    2370 provider.go:91] Refreshing cache for provider: *credentialprovider.defaultDockerConfigProvider
I0311 20:05:05.536375    2370 provider.go:91] Refreshing cache for provider: *gcp_credentials.dockerConfigKeyProvider
E0311 20:05:05.537279    2370 metadata.go:109] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
I0311 20:05:05.537306    2370 provider.go:91] Refreshing cache for provider: *gcp_credentials.dockerConfigUrlKeyProvider
E0311 20:05:05.539630    2370 metadata.go:121] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
I0311 20:05:09.793253    2370 event.go:92] Event(api.ObjectReference{Kind:"BoundPod", Namespace:"default", Name:"cadvisor-agent", UID:"cadvisormanifes12uqn2ohido76855gdecd9roadm7l0", APIVersion:"v1beta2", ResourceVersion:"", FieldPath:"spec.containers{cadvisor}"}): status
: 'waiting', reason: 'pulled' Successfully pulled image "google/cadvisor:latest"
I0311 20:05:09.851601    2370 event.go:92] Event(api.ObjectReference{Kind:"BoundPod", Namespace:"default", Name:"cadvisor-agent", UID:"cadvisormanifes12uqn2ohido76855gdecd9roadm7l0", APIVersion:"v1beta2", ResourceVersion:"", FieldPath:"spec.containers{cadvisor}"}): status
: 'waiting', reason: 'created' Created with docker id 9edda09a6c4d6211d31e3e3cd6cfcb7be8c4c13a448400b2348a55539f372ad0
I0311 20:05:09.937427    2370 event.go:92] Event(api.ObjectReference{Kind:"BoundPod", Namespace:"default", Name:"cadvisor-agent", UID:"cadvisormanifes12uqn2ohido76855gdecd9roadm7l0", APIVersion:"v1beta2", ResourceVersion:"", FieldPath:"spec.containers{cadvisor}"}): status
: 'running', reason: 'started' Started with docker id 9edda09a6c4d6211d31e3e3cd6cfcb7be8c4c13a448400b2348a55539f372ad0
E0311 20:05:24.403183    2370 http.go:54] Failed to read URL: http://metadata.google.internal/computeMetadata/v1beta1/instance/attributes/google-container-manifest: 404 Not Found
E0311 20:05:44.404841    2370 http.go:54] Failed to read URL: http://metadata.google.internal/computeMetadata/v1beta1/instance/attributes/google-container-manifest: 404 Not Found
I0311 20:06:01.135663    4797 server.go:163] Using root directory: /var/lib/kubelet
I0311 20:06:01.135729    4797 docker.go:794] Connecting to docker on unix:///var/run/docker.sock
I0311 20:06:01.136931    4797 util.go:76] Sending events to api server.
I0311 20:06:01.137022    4797 server.go:330] Adding manifest file: /etc/kubernetes/manifests
I0311 20:06:01.137039    4797 file.go:51] Watching path "/etc/kubernetes/manifests"
I0311 20:06:01.137050    4797 server.go:344] Watching apiserver
E0311 20:06:01.137166    4797 server.go:299] Failed to create kubelet: dial unix /var/run/docker.sock: connection refused
I0311 20:06:01.138359    4797 file.go:209] Got pod from file "/etc/kubernetes/manifests/cadvisor.manifest": file-6bb810db-k8s-staging-regtest-loop-2015-03-11-13-03-21-node-3.cadvisor-agent (4e66a84384c78f3929c39672c61e0558)
I0311 20:06:21.139892    4797 file.go:209] Got pod from file "/etc/kubernetes/manifests/cadvisor.manifest": file-6bb810db-k8s-staging-regtest-loop-2015-03-11-13-03-21-node-3.cadvisor-agent (98ba38643eac6da26ea029dcac795f0d)
I0311 20:06:41.141061    4797 file.go:209] Got pod from file "/etc/kubernetes/manifests/cadvisor.manifest": file-6bb810db-k8s-staging-regtest-loop-2015-03-11-13-03-21-node-3.cadvisor-agent (98ba38643eac6da26ea029dcac795f0d)
I0311 20:07:01.142354    4797 file.go:209] Got pod from file "/etc/kubernetes/manifests/cadvisor.manifest": file-6bb810db-k8s-staging-regtest-loop-2015-03-11-13-03-21-node-3.cadvisor-agent (98ba38643eac6da26ea029dcac795f0d)

**Comment by alex-mohr** [comment]
if I reboot a node, 3/3 times it also triggers this behavior.  If anyone does a kernel upgrade or a VM fails for maintenance and is restarted, presumably kubelet won't go healthy again later.  P0.

**Comment by vmarmol** [comment]
I merged #5187 a few days ago. This makes Kubelet wait up to 5min for Docker to come up. I don't think that went into 0.12.1. Does anyone know? I think that would alleviate this.

**Comment by vmarmol** [comment]
Just verified, this is not in 0.12.1. @alex-mohr can we try with that change? May be worth a cherrypick.

**Comment by dchen1107** [comment]
Shouldn't this is dupe of #5313?

**Comment by alex-mohr** [comment]
Maybe a dup of #5313 but I'm not convinced #5187 is a perfect fix: note the "failed to create kubelet" in the current log, but kubelet did not exit.  My read of #5187 is that it will also "failed to create kubelet", so unless there's something else that actually triggers a binary exit, we can still have the case where kubelet isn't responding?

**Comment by dchen1107** [comment]
Reassign it to myself to make sure I didn't miss any case beside #5313. But the fix in #5313 is not in 0.12.1 yet.

**Comment by alex-mohr** [comment]
Note that even though the proximate cause may be partially mitigated, the root cause I think is the mismatch between monit checking the pid and master checking /healthz on 10250.

Re: patching 12.1, we could, though it's somewhat a pain.  But I think this is easy enough to trigger (via reboots) that it's worthwhile -- will go kick that off.

**Comment by dchen1107** [comment]
@alex-mohr I agreed with you that #5187 is the perfect fix. Actually if node runs into the situation like #5313, #5187 doesn't help at all. 

@alex-mohr Can I ssh into one of your nodes?

**Comment by vmarmol** [comment]
They're completmentary, #5313 handles some of the cases where the Docker daemon in unreachable #5187 handles cases where it is temporarily unreachable. Having said that, we should be existing when that times out. That we don't today is a bug.

**Comment by dchen1107** [comment]
I checked bad node, and it is known issue: 

#5107 is fixed by #5120 (monit health check kubelet and restart unhealthy one)
#5313 is fixing when docker daemon unresponsible issue, could be deadlock, or whatever reasons. 

Somehow, I thought 0.12.1 does include #5120, but monit configure for kubelet, it doesn't do healthz check at all.

**Comment by dchen1107** [comment]
Dup of #5107

**Comment by dchen1107** [comment]
@alex-mohr  If you did include #5120 in 0.12.1, I guess you run into #5408 (push.sh doesn't really up the binaries). I ran into this problem since yesterday, and spent a lot of time on debugging my issues. :-(

**Comment by dchen1107** [comment]
Ok, I just proved my hyperthesis here:

root@k8s-staging-regtest-loop-2015-03-11-13-03-21-node-2:/var/log# kubelet --version
Kubernetes v0.12.0

It is NOT v0.12.1

**Comment by alex-mohr** [comment]
I am now officially completely embarrassed -- sorry for the false alarm!  I'll check versions more closely next time.

**Comment by dchen1107** [comment]
np at all. I did want to make sure both docker and kubelet are properly monitored and restarted when healthchecking failed. Let me know if you run into the similar situation next time.
