### ISSUE TITLE
kubectl.sh exec /bin/bash hangs after a while

### ISSUE THREAD

**Issue by rochaporto** [GoogleCloudPlatform/kubernetes#9180]
Hi.

This seems to happen consistently on a series of containers i run. As a test case i've used a centos7 image running /usr/sbin/init:
```
cat test-pod.yaml

metadata:
  name: test
  labels:
    name: test
spec:
  containers:
    - name: testcontainer
      image: centos:centos7
      command:
        - /usr/sbin/init
```
, on which i then do:
```
kubectl.sh exec -p test -c testcontainer -i -t -- /bin/bash
```

After a certain period of time without providing any input (even if there's a running command sending loads of output) the session hangs. A new session shows the command is still there (ps aux inside the container).

I don't see this happen if i use docker exec directly:
```
sudo docker ps | grep testcontainer
a1e7be0e50d6        centos:7                                         "/usr/sbin/init"       56 seconds ago      Up 56 seconds                           k8s_testcontainer.50b617ca_test_default_2fdf35d7-09ed-11e5-917f-2c413815e0ae_05f06e3f     

sudo docker exec -it a1e7be0e50d6 /bin/bash
```

Due to this i assume it's some extra kubernetes behavior. Let me know if i can provide any additional input - i couldn't find anything in the log files.

Thanks!

**Comment by wstrange** [comment]
+1 - I also see this.

Not a show stopper, but it is quite annoying

**Comment by bgrant0607** [comment]
cc @ncdc

**Comment by bgrant0607** [comment]
This is probably similar to the logs issue -- maybe the connection times out after 5 minutes. #9013

**Comment by rochaporto** [comment]
5 minutes sounds about right. Any way to have that timeout configurable?

**Comment by bgrant0607** [comment]
I'm not sure it's configurable.

There also might be multiple timeouts in play. We'd need to check the client code, the parameterized request timeout in the server, and the default read/write timeouts in the server. The latter is not configurable, and is here:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L53

See also:
https://github.com/openshift/origin/issues/2348

@ncdc @brenton

**Comment by trinitronx** [comment]
maybe `kubectl exec` should be doing TCP keepalives?

**Comment by ncdc** [comment]
The `kubectl exec` flow is client :arrow_right: master :arrow_right: kubelet :arrow_right: container. The kubelet http server has a 5 minute read/write timeout (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/server.go#L68-L69). This unfortunately means that after 5 minutes, regardless of the amount of I/O generated during the exec session, the connection is forcibly closed (assuming I'm interpreting the definitions of ReadTimeout and WriteTimeout correctly from http://golang.org/pkg/net/http/#Server).

@smarterclayton FYI

**Comment by smarterclayton** [comment]
We may want to bump that timeout (apiserver is 60 minutes right now).

We really need timeouts per connection type (including better idle timeouts) and a garbage collector than can close outstanding connections by class of the kubelet is under stress.

**Comment by erictune** [comment]
Seen today multiple times from build at head today.

**Comment by ncdc** [comment]
@erictune what did you see specifically?

**Comment by krousey** [comment]
Can I just remove the timeout at the kubelet layer since we have timeouts at the master? Or do we wish to maintain timeouts in both places?

As far as the timeouts go, it's probably a mistake to have them be server wide. Note that these are not idle timeouts, they are absolute deadlines. I would suggest we do them per handler with http.TimeoutHandler, but the ResponseWriter you get from that may only has Write and WriteHeader methods. You would not be able to type assert to http.Hijacker or http.CloseNotifier. I don't know how much and which paths depend on that. Perhaps we only need it on the paths that we don't want timeouts. I could also reimplement http.TimeoutHandler with a response writer that does implement these. Then we could wrap it like MaxInFlightLimit.

Thoughts on this?

```
> find . -type f -name '*.go' -exec grep -n 'http.CloseNotifier' {} \+
./pkg/apiserver/watch.go:140:	cn, ok := w.(http.CloseNotifier)
./Godeps/_workspace/src/github.com/google/cadvisor/api/handler.go:137:	cn, ok := w.(http.CloseNotifier)
./Godeps/_workspace/src/github.com/google/cadvisor/api/handler.go:139:		return errors.New("could not access http.CloseNotifier")
./Godeps/_workspace/src/github.com/codegangsta/negroni/response_writer.go:82:	return rw.ResponseWriter.(http.CloseNotifier).CloseNotify()
./Godeps/_workspace/src/github.com/codegangsta/negroni/response_writer_test.go:134:	notifier := rw.(http.CloseNotifier).CloseNotify()
./Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:243:// CloseNotify is part of http.CloseNotifier interface
./Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:245:	return r.ResponseWriter.(http.CloseNotifier).CloseNotify()
./Godeps/_workspace/src/github.com/emicklei/go-restful/compress.go:41:// CloseNotify is part of http.CloseNotifier interface
./Godeps/_workspace/src/github.com/emicklei/go-restful/compress.go:43:	return c.writer.(http.CloseNotifier).CloseNotify()
```

```
> find . -type f -name '*.go' -exec grep -n 'http.Hijacker' {} \+     
./pkg/util/httpstream/spdy/upgrade.go:54:	hijacker, ok := w.(http.Hijacker)
./pkg/apiserver/proxy.go:231:	requestHijackedConn, _, err := w.(http.Hijacker).Hijack()
./pkg/httplog/log.go:196:// Hijack implements http.Hijacker.
./pkg/httplog/log.go:198:	return rl.w.(http.Hijacker).Hijack()
./pkg/registry/generic/rest/proxy.go:132:	requestHijackedConn, _, err := w.(http.Hijacker).Hijack()
./Godeps/_workspace/src/golang.org/x/net/websocket/server.go:74:	rwc, buf, err := w.(http.Hijacker).Hijack()
./Godeps/_workspace/src/github.com/codegangsta/negroni/response_writer.go:74:	hijacker, ok := rw.ResponseWriter.(http.Hijacker)
./Godeps/_workspace/src/github.com/codegangsta/negroni/response_writer_test.go:111:	hijacker, ok := rw.(http.Hijacker)
./Godeps/_workspace/src/github.com/codegangsta/negroni/response_writer_test.go:123:	hijacker, ok := rw.(http.Hijacker)
./Godeps/_workspace/src/github.com/fsouza/go-dockerclient/testing/server.go:536:	hijacker, ok := w.(http.Hijacker)
./Godeps/_workspace/src/github.com/fsouza/go-dockerclient/container_test.go:1080:		hj, ok := w.(http.Hijacker)
./Godeps/_workspace/src/github.com/docker/spdystream/spdy_test.go:812:		netconn, _, _ := w.(http.Hijacker).Hijack()
```

**Comment by smarterclayton** [comment]
I don't know that TimeoutHandler is lower level enough - we want to have
that be applied almost at the Filter level of an individual restful
Container WebService (per type) - i.e. the CONNECT / PROXY / WATCH
behaviors should all be handled like this, and then log retrieval is inside
of a particular handler.  I would think we would want a helper to apply to
a given http.ResponseWriter and propagate the timeout values via the
initializer for the handlers, which would then impose.  The top level
imposition seems wrong, I agree.

On Mon, Jun 29, 2015 at 6:42 PM, krousey <notifications@github.com> wrote:

> Can I just remove the timeout at the kubelet layer since we have timeouts
> at the master? Or do we wish to maintain timeouts in both places?
>
> As far as the timeouts go, it's probably a mistake to have them be server
> wide. Note that these are not idle timeouts, they are absolute deadlines. I
> would suggest we do them per handler with http.TimeoutHandler, but the
> ResponseWriter you get from that may only has Write and WriteHeader
> methods. You would not be able to type assert to http.Hijacker or
> http.CloseNotifier. I don't know how much and which paths depend on that.
> Perhaps we only need it on the paths that we don't want timeouts. I could
> also reimplement http.TimeoutHandler with a response writer that does
> implement these. Then we could wrap it like MaxInFlightLimit.
>
> Thoughts on this?
>
> > find . -type f -name '*.go' -exec grep -n 'http.CloseNotifier' {} \+
> ./pkg/apiserver/watch.go:140:   cn, ok := w.(http.CloseNotifier)
> ./Godeps/_workspace/src/github.com/google/cadvisor/api/handler.go:137:  cn, ok := w.(http.CloseNotifier)
> ./Godeps/_workspace/src/github.com/google/cadvisor/api/handler.go:139:      return errors.New("could not access http.CloseNotifier")
> ./Godeps/_workspace/src/github.com/codegangsta/negroni/response_writer.go:82:   return rw.ResponseWriter.(http.CloseNotifier).CloseNotify()
> ./Godeps/_workspace/src/github.com/codegangsta/negroni/response_writer_test.go:134: notifier := rw.(http.CloseNotifier).CloseNotify()
> ./Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:243:// CloseNotify is part of http.CloseNotifier interface
> ./Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:245: return r.ResponseWriter.(http.CloseNotifier).CloseNotify()
> ./Godeps/_workspace/src/github.com/emicklei/go-restful/compress.go:41:// CloseNotify is part of http.CloseNotifier interface
> ./Godeps/_workspace/src/github.com/emicklei/go-restful/compress.go:43:  return c.writer.(http.CloseNotifier).CloseNotify()
>
> > find . -type f -name '*.go' -exec grep -n 'http.Hijacker' {} \+
> ./pkg/util/httpstream/spdy/upgrade.go:54:   hijacker, ok := w.(http.Hijacker)
> ./pkg/apiserver/proxy.go:231:   requestHijackedConn, _, err := w.(http.Hijacker).Hijack()
> ./pkg/httplog/log.go:196:// Hijack implements http.Hijacker.
> ./pkg/httplog/log.go:198:   return rl.w.(http.Hijacker).Hijack()
> ./pkg/registry/generic/rest/proxy.go:132:   requestHijackedConn, _, err := w.(http.Hijacker).Hijack()
> ./Godeps/_workspace/src/golang.org/x/net/websocket/server.go:74:    rwc, buf, err := w.(http.Hijacker).Hijack()
> ./Godeps/_workspace/src/github.com/codegangsta/negroni/response_writer.go:74:   hijacker, ok := rw.ResponseWriter.(http.Hijacker)
> ./Godeps/_workspace/src/github.com/codegangsta/negroni/response_writer_test.go:111: hijacker, ok := rw.(http.Hijacker)
> ./Godeps/_workspace/src/github.com/codegangsta/negroni/response_writer_test.go:123: hijacker, ok := rw.(http.Hijacker)
> ./Godeps/_workspace/src/github.com/fsouza/go-dockerclient/testing/server.go:536:    hijacker, ok := w.(http.Hijacker)
> ./Godeps/_workspace/src/github.com/fsouza/go-dockerclient/container_test.go:1080:       hj, ok := w.(http.Hijacker)
> ./Godeps/_workspace/src/github.com/docker/spdystream/spdy_test.go:812:      netconn, _, _ := w.(http.Hijacker).Hijack()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/9180#issuecomment-116872091>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by krousey** [comment]
Also the server level read and write timeouts don't even close TCP sessions. It just makes the writes and reads error. The TCP session doesn't end until the handler returns (or close it manually if you hijack the net.Conn).

**Comment by ncdc** [comment]
@krousey yeah, it took me a while to figure out that was happening. Not a great UX.

**Comment by krousey** [comment]
I'm trying to put in a fix to increase the kubelet timeouts to 1 hour to match the master. Unfortunately adding proper timeout handling for these cases may not make 1.0, but hopefully this can make it less annoying.

**Comment by bgrant0607** [comment]
1 hour would be much better than 5 minutes. Thanks.

**Comment by krousey** [comment]
This should be fixed now.

**Comment by rroopreddy** [comment]
I am working with release 1.0.6 have the same problem Based on the date of this issue, it suggests that this would have been fixed in this latest version. Am I missing something?

**Comment by antoineco** [comment]
It's fixed from v1.1.0 onwards, but this was not cherry picked in v1.0.6 or before.

**Comment by deitch** [comment]
Is it possible this is back in 1.6.2 (didn't check 1.6.1 or 1.6.0)? I have several containers that just bump me out of a `kubectl exec -it <pod> sh` after a few mins (I think it is <5, but didn't time precisely).

Or is it a config option?

**Comment by deitch** [comment]
Yep. 60 seconds and I get booted. kubelet is set with option `--v=2`, and the only things in the logs the entire time are the connection to exec and a bunch of `MountVolume.SetUp` successes:

```
May 14 10:54:53 ip-10-50-20-229.ec2.internal kubelet[3962]: I0514 10:54:53.514140    3962 server.go:778] GET /cri/exec/pxc7AuM0: (8.15633176s) hijacked [[kubectl/v1.6.1 (darwin/amd64) kubernetes/b0b7a32] 10.50.21.32:46376]
May 14 10:54:57 ip-10-50-20-229.ec2.internal kubelet[3962]: I0514 10:54:57.898270    3962 server.go:778] POST /exec/default/kafka-2-2847540175-6rjn2/kafka?command=sh&error=1&input=1&output=1&tty=1: (5.625355ms) 302 [[kubectl/v1.6.1 (darwin/amd64) kubernetes/b0b7a32] 10.50.20.120:41810]
May 14 10:54:58 ip-10-50-20-229.ec2.internal kubelet[3962]: I0514 10:54:58.119106    3962 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/b22404c5-361d-11e7-b5ad-1229c2369db0-weave-net-token-gt7qm" (spec.Name: "weave-net-token-gt7qm") pod "b22404c5-361d-11e7-b5ad-1229c2369db0" (UID: "b22404c5-361d-11e7-b5ad-1229c2369db0").
May 14 10:55:12 ip-10-50-20-229.ec2.internal kubelet[3962]: I0514 10:55:12.050709    3962 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/9435e4d7-365c-11e7-b5ad-1229c2369db0-default-token-dtll7" (spec.Name: "default-token-dtll7") pod "9435e4d7-365c-11e7-b5ad-1229c2369db0" (UID: "9435e4d7-365c-11e7-b5ad-1229c2369db0").
May 14 10:55:16 ip-10-50-20-229.ec2.internal kubelet[3962]: I0514 10:55:16.059495    3962 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/6a63a1bc-387a-11e7-b5ad-1229c2369db0-default-token-dtll7" (spec.Name: "default-token-dtll7") pod "6a63a1bc-387a-11e7-b5ad-1229c2369db0" (UID: "6a63a1bc-387a-11e7-b5ad-1229c2369db0").
May 14 10:55:17 ip-10-50-20-229.ec2.internal kubelet[3962]: I0514 10:55:17.061718    3962 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/a4b0f18f-3742-11e7-b5ad-1229c2369db0-default-token-dtll7" (spec.Name: "default-token-dtll7") pod "a4b0f18f-3742-11e7-b5ad-1229c2369db0" (UID: "a4b0f18f-3742-11e7-b5ad-1229c2369db0").




May 14 10:55:46 ip-10-50-20-229.ec2.internal kubelet[3962]: I0514 10:55:46.133680    3962 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/999e3f6b-361e-11e7-b5ad-1229c2369db0-default-token-zjdc0" (spec.Name: "default-token-zjdc0") pod "999e3f6b-361e-11e7-b5ad-1229c2369db0" (UID: "999e3f6b-361e-11e7-b5ad-1229c2369db0").
May 14 10:55:48 ip-10-50-20-229.ec2.internal kubelet[3962]: I0514 10:55:48.657737    3962 qos_container_manager_linux.go:285] [ContainerManager]: Updated QoS cgroup configuration


May 14 10:55:51 ip-10-50-20-229.ec2.internal kubelet[3962]: I0514 10:55:51.043644    3962 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/9993422b-361e-11e7-b5ad-1229c2369db0-default-token-dtll7" (spec.Name: "default-token-dtll7") pod "9993422b-361e-11e7-b5ad-1229c2369db0" (UID: "9993422b-361e-11e7-b5ad-1229c2369db0").
May 14 10:55:54 ip-10-50-20-229.ec2.internal kubelet[3962]: I0514 10:55:54.050521    3962 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/b223eff9-361d-11e7-b5ad-1229c2369db0-default-token-zjdc0" (spec.Name: "default-token-zjdc0") pod "b223eff9-361d-11e7-b5ad-1229c2369db0" (UID: "b223eff9-361d-11e7-b5ad-1229c2369db0").
May 14 10:55:54 ip-10-50-20-229.ec2.internal kubelet[3962]: I0514 10:55:54.051680    3962 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/configmap/b223eff9-361d-11e7-b5ad-1229c2369db0-traefik-tmpl" (spec.Name: "traefik-tmpl") pod "b223eff9-361d-11e7-b5ad-1229c2369db0" (UID: "b223eff9-361d-11e7-b5ad-1229c2369db0").
May 14 10:55:57 ip-10-50-20-229.ec2.internal kubelet[3962]: I0514 10:55:57.057528    3962 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/cd8f7d06-3746-11e7-b5ad-1229c2369db0-default-token-dtll7" (spec.Name: "default-token-dtll7") pod "cd8f7d06-3746-11e7-b5ad-1229c2369db0" (UID: "cd8f7d06-3746-11e7-b5ad-1229c2369db0").
May 14 10:56:13 ip-10-50-20-229.ec2.internal kubelet[3962]: I0514 10:56:13.093467    3962 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/9435e4d7-365c-11e7-b5ad-1229c2369db0-default-token-dtll7" (spec.Name: "default-token-dtll7") pod "9435e4d7-365c-11e7-b5ad-1229c2369db0" (UID: "9435e4d7-365c-11e7-b5ad-1229c2369db0").
```

Nothing for being kicked out, though.

**Comment by RiaanLab** [comment]
I am using v1.6.2 and I can confirm that the timeout is definitely still happening in less than 10 minutes.

**Comment by deitch** [comment]
10 minutes sounds great! I wish I could get it that high. Any idea what controls the timeout?

**Comment by RiaanLab** [comment]
@deitch I have no idea what sets the timeout, only that the terminal hangs/freezes in less than 10min.

**Comment by deitch** [comment]
Interesting. More often I see it get kicked out after 1 min rather than hang.

**Comment by dlouzan** [comment]
@deitch @RiaanLab Might it be the case that you are using this in AWS? I had the same issue and the reason was the ELB in front of the API server, by default it has a 60 seconds timeout. If there's no traffic, the connection will be dropped.

**Comment by deitch** [comment]
@dlouzan yes, that was the case indeed. I haven't seen the issue in a while, but as our CD pipeline has matured, we have used it much less, so that is more indicative of lack of usage than lack of problem.

**Comment by RiaanLab** [comment]
Nope, I am not using it on AWS. Thanks for the response though.

**Comment by Mart-Bogdan** [comment]
We are running into this issue in `v1.9.2`
